FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/python:3.11

RUN sudo apt -y update
RUN sudo apt -y install libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0